### ISSUE TITLE
must manually install cython via pip

### ISSUE THREAD

**Issue by ghost** [fccoelho/epigrass#2]
Here is the error when installing epigrass
```
pip3 install epigrass
Collecting epigrass
  Downloading https://files.pythonhosted.org/packages/4e/b1/b1ea10683666fa5036f237a0b83537009e873fc7294818800b62cbc0eaf5/epigrass-2.6.1.tar.gz (4.9MB)
    100% |████████████████████████████████| 4.9MB 236kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bdcxn_8w/epigrass/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bdcxn_8w/epigrass/
```

Of course the manual solution is extremely easy
```pip3 install cython```

However, you successfully pull in things like numpy, so this should be easy to remedy

**Comment by fccoelho** [comment]
I'll add this to the install_requires in the setup.py

**Comment by fccoelho** [comment]
I have added it to setup_requires on setup.py. As soon as I finish some other issues, I'll make another release
